version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"

  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `example` directory
    directory: "/example"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
