variables:
  GIT_SUBMODULE_STRATEGY: recursive
  SONAR_REFERENCE_BRANCH: origin/develop

stages:
  - build
  - test
  - sonar
  - publish

build-package:
  image: 'gitlab.ta.philips.com:5432/forest/docker/node-ci:9.11.1'
  stage: build
  script:
    - ./ci/forest/bin/build.sh

  artifacts:
    paths:
      - ./dist
    expire_in: 1 day

  cache:
    key: "$CI_BUILD_REF"
    untracked: true


test-package:
  image: gitlab.ta.philips.com:5432/forest/docker/node-ci:9.11.1
  stage: test
  script:
    - ./ci/forest/bin/test.sh

  artifacts:
    paths:
      - ./dist
      - ./coverage
    expire_in: 1 day

  tags:
    - docker

sonar_preview:
  image: gitlab.ta.philips.com:5432/forest/docker/sonar-ci:3.1.0.1141
  stage: sonar
  script:
    - ./ci/forest/bin/sonar-preview.sh
  except:
    - develop
    - master
    - tags

sonar:
  image: gitlab.ta.philips.com:5432/forest/docker/sonar-ci:3.1.0.1141
  stage: sonar
  script:
    - ./ci/forest/bin/sonar.sh
  only:
    - tags
    - develop
    - master

pages:
  image: 'gitlab.ta.philips.com:5432/forest/docker/node-ci:9.11.1'
  stage: build
  script:
    - yarn
    - yarn build-storybook
  artifacts:
    paths:
      - public
  only:
    - tags

publish-package:
  image: 'gitlab.ta.philips.com:5432/forest/docker/node-ci:9.11.1'
  stage: publish
  script:
    - ./ci/forest/bin/publish-npm-package.sh

  artifacts:
    paths:
      - ./dist
    expire_in: 1 day

  only:
    - tags

  cache:
    key: "$CI_BUILD_REF"
    untracked: true
