language: node_js
cache: yarn
node_js:
- 8
script:
- yarn lint
- yarn test
deploy:
  skip_cleanup: true
  provider: npm
  email: jasper@strnk.nl
  api_key:
    secure: RkkN+hx6FvKCU8bi0mULJMPWPNais2NJfkog0jpMGZ+LWq45tAChKAskmOwYDupufMtWI/6IH127fq3KdBnM+R0x7J9QHOGpYO2tSY6cy2H9AMYEq0GjbE6xzZIhS5Nb4+CXeD1w9WBNtqLwzea7mOkCJCrbb5XBQIwx2rCdNxRJemGvQW21enBf1gQpssViHofbgrAL4Te7ViEk8twSgkTpP+wnIhP7lM+srEAOHllPrUnf32SShakw7lbj+rhHh6MKYI+Ie1OwcD3hUlcKNKZnl0nXCR7xUxgBS/i2XjPSNH8Kte/o97S7N2YQsBxsvsapnO3T8k/XrPAE3E9v2g7dsuIh1qeB8lVH3Je46jXPHCDPHrbkpK5SA0PF/aNjbwPAW319xhITkThpNE2T3mLd3JUQA0v9XcjrXin4WMsaixgQj5/qSSatbokjTIYzJEkYzKYfwE/uGV7RS64t8gSBx6yXLO3brocrtK+Oic9k43vy880mo+07xfgjUudcJ68vz4fHfRlZvXToOEjuGAW5lytQJr7qFnk4jeUN26jSnrZCorqStmJlaAr5Q8ztHkEyswzlcEBWfSDBU21lGdTqUp0LXFDKsLeGvbJC2AvRx1vzwfaIuzowJEJqQw4T3tOmEJFdTt6w9GmcoVoIwpUvWaOz+BTsyQdAcb3lF0g=
  on:
    tags: true
    branch: master
